### ISSUE TITLE
Streaming to multiple ESP32 modules via router

### ISSUE THREAD

**Issue by codePavan** [rkinnett/ESP32-VBAN-Network-Audio-Player#1]
Hello,
Is it possible to use the same application to stream to multiple ESP32 modules, like all the esp32 modules connected to the router with a certain configuration can receive the audio?

**Comment by rkinnett** [comment]
It's been five years since I looked at this, but I think I vaguely recall that there may be a way to "broadcast" (no specific destination address) from VBAN, and it's probably easy to pick that up on the ESP32s.  I think I looked into the opposite configuration, broadcasting sampled audio from the ESP32 over the network, but I couldn't pick it up in VBAN due to router limitations, or maybe VBAN picket it up but the stream bandwidth was severely limited by the router.  I don't remember exactly.  Anyway, good question, but it's not in scope of this project, so I'll close this ticket but feel free to comment here.
